//  namespace can be without a name
// In unnamed namespace name of the namespace is not mentioned.
// They are directly usable in same program and are used for declaring unique identifier.
// name of the namespace is uniquely generated by the compiler.
// This will be accessible within the file you created.
// this is the replacement for the static declaration of the variable 


#include <iostream>
using namespace std;

namespace 
{
    int a=5;
}

int main()
{
    cout<<"value of a = "<<a<<endl;
}